services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "HWheelsDb"
      POSTGRES_USER: "root_user"
      POSTGRES_PASSWORD: "root_password"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

